#!/bin/bash

export GITHUB_USERNAME="123keerthan123"
export GITHUB_REPOSITORY="cs1102-24f2100303"

echo "GITHUB_USERNAME is set to $GITHUB_USERNAME"
echo "GITHUB_REPOSITORY is set to $GITHUB_REPOSITORY"

